name: GalacticKillStreaks
main: me.eaz.galactickillstreaks.GalacticKillStreaks
version: 1.0.0
author: Eaz
description: Advanced killstreak, bounty and reward system for GalacticPVP
depend:
  - Vault
  - BountyHunters
softdepend:
  - PlaceholderAPI

commands:
  gks:
    description: GalacticKillStreaks admin command
    usage: /gks
    permission: galactickillstreaks.admin

  killstreak:
    description: View your killstreak
    aliases:
      - ks

  topstreaks:
    description: View the top killstreak leaderboard
    aliases:
      - topks

  record:
    description: View the server killstreak record

permissions:
  galactickillstreaks.admin:
    description: Access to all GalacticKillStreaks admin commands
    default: op

  galactickillstreaks.use:
    description: Allows use of player commands
    default: true
